// If I break up the manager enough, I might be able to call each assignment separately, and check the results...
// I think really though I'd have to make sure the assignments exist for each... which means a lot of updates to the objects... could be very hard

// I'll put this down as a to-do for later for now... I think it's possible though... 
// It could even check paths like falling to spawning or load managing etc if I wanted it to