// The idea of this helper is to meet demand... the assignments raise demand, and the hubs/spawns supply it
// The eventual goal is to remove the dependancy on the config creep counts and let the code figure out what should happen...
// I think this might only be for hub assignments... externals should never be limited...

// I would be controlling the equalizer in the hub assignments...
	// If assignments but no assignees/spawning, then increase demand
	// Else, decrease demand until 0...

// It would be possible to make equalizer a property of hub
	// hub.memory.equalizer...
